### ISSUE TITLE
Integrating with Jest + Bore

### ISSUE THREAD

**Issue by mattdsteele** [skatejs/ssr#2]
This isn't so much an issue as it is a collection of questions around how one should go about getting Jest working with WCs. If you'd prefer

Using skatejs, jest, bore, and ssr as described in https://github.com/skatejs/ssr/issues/1. If you'd prefer these be separate issues let me know.

## Vanilla WCs

Using JSX seems to work okay, but defining elements as strings fails:

```javascript
describe('Vanilla WCs', () => {
    class VanillaComponent extends HTMLElement {
        connectedCallback() {
            this.attachShadow({ mode: 'open' });
            this.shadowRoot.innerHTML = '<p>Created!</p>';
        }
    }
    customElements.define('vanilla-wc', VanillaComponent);
    it('works with vanilla WCs (jsx)', () => {
        const wrapper = mount(<VanillaComponent />);
        expect(wrapper.node.nodeName).toEqual('VANILLA-WC');
        expect(wrapper.has(<p>Created!</p>)).toBeTruthy();
    });

    it('does not work with string elements', () => {
        const wrapper = mount('<vanilla-wc></vanilla-wc>');
        expect(wrapper.node.nodeName).toEqual('VANILLA-WC');
    })
})
```

Second test fails with:
```
FAIL  test\components.spec.tsx
  ● Vanilla WCs › does not work with string elements

    TypeError: Cannot redefine property: shadowRoot
        at defineProperty (native)

      at VanillaComponent.attachShadow (../../node_modules/@skatejs/ssr/register.js:164:7)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
      at VanillaComponent.HTMLElement.attachShadow (../../node_modules/@skatejs/bore/umd/@sk
atejs/bore.js:120:23)
```

The second test seems to be related to https://github.com/skatejs/bore/pull/12 but I thought that was resolved?

## Skate Components

I haven't been able to get any Skate components to run:

```javascript
const { h } = require('@skatejs/val');
const { mount } = require('@skatejs/bore');
const { Component } = require('skatejs');
describe('Skate components', () => {
    class SkateComponent extends Component<void> {
        connectedCallback() {
            console.log('In Skate Component');
        }
    }
    customElements.define('skate-wc', SkateComponent);
    it('does not register properly', () => {
        const wrapper = mount(<SkateComponent />);
    });
})
```

Fails with:

```
 ● Skate components › does not register properly

    TypeError: Class constructor  cannot be invoked without 'new'

      at SkateComponent._class2 (node_modules/skatejs/umd/skatejs.js:240:58)
      at SkateComponent._class (node_modules/skatejs/umd/skatejs.js:463:53)
      at SkateComponent._class (node_modules/skatejs/umd/skatejs.js:408:53)
      at SkateComponent._class (node_modules/skatejs/umd/skatejs.js:788:59)
      at SkateComponent (test/components.spec.tsx:27:5)
      at Document.document.createElement (../../node_modules/@skatejs/ssr/register.js:74:25)

      at defaultCreateElement (../../node_modules/@skatejs/val/umd/@skatejs/val.js:207:67)
      at ../../node_modules/@skatejs/val/umd/@skatejs/val.js:236:26
      at Object.it (test/components.spec.tsx:34:31)
```

Since it's running in a native ES6 environment, I think it's the old chestnut of transpiled CEs not working without native-shim.

I tried loading `@web-components/custom-elements/src/native-shim` but that was failing because `navigator` was undefined.

Also tried loading the ES2015 sources from `skatejs/es`, but those fail since they're using ESM modules, to Node's chagrin.

So mostly I'm looking for a pattern I can use to test my Skate components. I think I could do it by running it through Webpack to produce a CJS module but I'm wondering if there's a more 'appropriate' way to do it?

**Comment by treshugart** [comment]
> TypeError: Cannot redefine property: shadowRoot

This is because when you use a string, it ends up calling `connectedCallback()` twice due to the way it parses and inserts. We may be able to eliminate the need for this in the future, however, this is standards compliant, it just doesn't give you the same error message. To get around this, simply guard `if (!this.shadowRoot)` etc.

I've released a bore 4.0.1 that fixes a couple things and better tests the string behaviour, but it's likely you won't need it if you just guard.

> I haven't been able to get any Skate components to run:

There's two issues here, one of them you haven't encountered yet.

1. Use the `skatejs/esnext` source instead of `es`.
2. Make sure you callback to `super.connectedCallback()`.
