### ISSUE TITLE
skatejs/ssr not running

### ISSUE THREAD

**Issue by rogi29** [skatejs/ssr#29]
D:\xampp\htdocs\architect\core\node_modules\@skatejs\ssr\register\util.js:15
  const { context, ...args } = opts;
                   ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\xampp\htdocs\architect\core\node_modules\babel-re
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\xampp\htdocs\architect\core\node_modules\@skatejs\ssr\register\index.js:7:20)

**Comment by treshugart** [comment]
What version of node are you using?

**Comment by treshugart** [comment]
The nvmrc specifies 8.4, but we haven't specified engines in the package.json for it.

**Comment by rogi29** [comment]
Oh, it might be an older version, I will check it out, thank you!

**Comment by treshugart** [comment]
@rogi29 cool, please let me know.

**Comment by treshugart** [comment]
Closing because this repo has been moved over to the main skatejs monorepo. Please open there if it's still an issue. Thanks!
