### ISSUE TITLE
TypeError: Class constructor cannot be invoked without 'new' - when try to render the skate.js component.

### ISSUE THREAD

**Issue by majo44** [skatejs/ssr#4]
Full example:
```
require('@skatejs/ssr/register');
let render = require('@skatejs/ssr');
let { Component, h } = require('skatejs');

class XHello extends Component {
    static get props() {
        return {
            name: {attribute: true}
        }
    }

    get renderRoot() {
        return this;
    }
    renderCallback () {
        return h('span', null, `Hello, Pawel`);
    }
}
customElements.define('x-hello', XHello);
let hello = new XHello();
render(hello).then(console.log);
```
The error:
```
C:\Users\majo4\Projects\private\skatejs-ssr\node_modules\skatejs\umd\skatejs.js:240
      var _this = _possibleConstructorReturn(this, _Base.call(this));
                                                         ^

TypeError: Class constructor  cannot be invoked without 'new'
    at XHello._class2 (C:\Users\majo4\Projects\private\skatejs-ssr\node_modules\skatejs\umd\skatejs.js:240:58)
    at XHello._class (C:\Users\majo4\Projects\private\skatejs-ssr\node_modules\skatejs\umd\skatejs.js:463:53)
    at XHello._class (C:\Users\majo4\Projects\private\skatejs-ssr\node_modules\skatejs\umd\skatejs.js:408:53)
    at XHello._class (C:\Users\majo4\Projects\private\skatejs-ssr\node_modules\skatejs\umd\skatejs.js:788:59)
    at XHello (C:\Users\majo4\Projects\private\skatejs-ssr\test.js:13:1)
    at Object.<anonymous> (C:\Users\majo4\Projects\private\skatejs-ssr\test.js:42:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

Process finished with exit code 1
```
Fix:
```
require('@skatejs/ssr/register');
let origHTMLElement = HTMLElement;
HTMLElement = function() {
    let newTarget = this.constructor;
    return Reflect.construct(origHTMLElement, [], newTarget);
};
HTMLElement.prototype = Object.create(origHTMLElement.prototype, {
    constructor: {value: HTMLElement, configurable: true, writable: true},
});
let render = require('@skatejs/ssr');
let { Component, h } = require('skatejs');
...
```

Please consider to add native HTMLElement constructor shim  under '@skatejs/ssr/register'
Regards.

**Comment by treshugart** [comment]
@majo44 Would be super stoked if you wanted to pr this! :). The workaround currently is to import from `skatejs/es-latest` (or soon to be `esnext`).
